vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Apr 2007 16:06:00 -0000
vti_extenderversion:SR|6.0.2.6551
vti_author:SR|JM-CHFU\\Jm.fu
vti_modifiedby:SR|JM-CHFU\\Jm.fu
vti_timecreated:TR|22 Apr 2007 16:06:00 -0000
vti_cacheddtm:TX|22 Apr 2007 16:06:00 -0000
vti_filesize:IR|28805
vti_cachedlinkinfo:VX|H|Admin.Asp H|Admin.Asp H|Admin.Asp S|http://www.yimxu.com/js/ver.js A|Admin.Asp A|Admin.Asp A|Admin.Asp H|Admin.Asp H|Admin.Asp S|../images/del.gif H|Admin.Asp H|Admin.Asp S|../images/del.gif H|Admin.Asp S|../images/del.gif H|Admin.Asp S|../images/mail.gif S|../images/face/<%=Rs(9)%>.gIf H|javascript:history.go(-1)
vti_cachedsvcrellinks:VX|FHUS|bbs/Admin/Admin.Asp FHUS|bbs/Admin/Admin.Asp FHUS|bbs/Admin/Admin.Asp NSHS|http://www.yimxu.com/js/ver.js FAUS|bbs/Admin/Admin.Asp FAUS|bbs/Admin/Admin.Asp FAUS|bbs/Admin/Admin.Asp FHUS|bbs/Admin/Admin.Asp FHUS|bbs/Admin/Admin.Asp FSUS|bbs/images/del.gif FHUS|bbs/Admin/Admin.Asp FHUS|bbs/Admin/Admin.Asp FSUS|bbs/images/del.gif FHUS|bbs/Admin/Admin.Asp FSUS|bbs/images/del.gif FHUS|bbs/Admin/Admin.Asp FSUS|bbs/images/mail.gif USUS|../images/face/<%=Rs(9)%>.gIf SHUS|javascript:history.go(-1)
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|gb2312
vti_backlinkinfo:VX|bbs/Admin/Index.Asp bbs/Admin/Admin.Asp
