vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Apr 2007 13:51:00 -0000
vti_extenderversion:SR|6.0.2.6551
vti_author:SR|JM-CHFU\\Jm.fu
vti_modifiedby:SR|JM-CHFU\\Jm.fu
vti_timecreated:TR|22 Apr 2007 13:51:00 -0000
vti_cacheddtm:TX|22 Apr 2007 13:51:00 -0000
vti_filesize:IR|30000
vti_cachedlinkinfo:VX|A|Admin1.Asp A|Admin1.Asp H|<%=Rs("Url")%> H|Admin1.Asp S|../images/edit.gif H|Admin1.Asp S|../images/del.gif A|Admin1.Asp A|Admin1.Asp A|Admin1.Asp A|Admin1.Asp A|Admin1.Asp A|Admin1.Asp S|../images/hr1.gif S|../images/hr2.gif S|../images/hr4.gif S|../images/hr5.gif S|../images/hr6.gif S|../images/hr1.gif S|../images/hr2.gif S|../images/hr3.gif
vti_cachedsvcrellinks:VX|FAUS|bbs/Admin/Admin1.Asp FAUS|bbs/Admin/Admin1.Asp UHUS|<%=Rs("Url")%> FHUS|bbs/Admin/Admin1.Asp FSUS|bbs/images/edit.gif FHUS|bbs/Admin/Admin1.Asp FSUS|bbs/images/del.gif FAUS|bbs/Admin/Admin1.Asp FAUS|bbs/Admin/Admin1.Asp FAUS|bbs/Admin/Admin1.Asp FAUS|bbs/Admin/Admin1.Asp FAUS|bbs/Admin/Admin1.Asp FAUS|bbs/Admin/Admin1.Asp FSUS|bbs/images/hr1.gif FSUS|bbs/images/hr2.gif FSUS|bbs/images/hr4.gif FSUS|bbs/images/hr5.gif FSUS|bbs/images/hr6.gif FSUS|bbs/images/hr1.gif FSUS|bbs/images/hr2.gif FSUS|bbs/images/hr3.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|gb2312
vti_backlinkinfo:VX|bbs/Admin/Admin1.Asp bbs/Admin/Index.Asp
