vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|19 May 2007 17:39:00 -0000
vti_extenderversion:SR|6.0.2.6551
vti_author:SR|JM-CHFU\\Jm.fu
vti_modifiedby:SR|JM-CHFU\\Jm.fu
vti_timecreated:TR|19 May 2007 17:39:00 -0000
vti_cacheddtm:TX|19 May 2007 17:39:00 -0000
vti_filesize:IR|3869
vti_cachedlinkinfo:VX|S|Images/Inputbg.gif
vti_cachedsvcrellinks:VX|NSUS|bbs/Admin/Images/Inputbg.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_charset:SR|gb2312
vti_backlinkinfo:VX|
