vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Apr 2007 13:51:00 -0000
vti_extenderversion:SR|6.0.2.6551
vti_author:SR|JM-CHFU\\Jm.fu
vti_modifiedby:SR|JM-CHFU\\Jm.fu
vti_timecreated:TR|22 Apr 2007 13:51:00 -0000
vti_cacheddtm:TX|22 Apr 2007 13:51:00 -0000
vti_filesize:IR|4276
vti_cachedlinkinfo:VX|S|Images/Inputbg.gif
vti_cachedsvcrellinks:VX|NSUS|bbs/Admin/Images/Inputbg.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|gb2312
vti_backlinkinfo:VX|bbs/Admin/Index.Asp
