vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Apr 2007 13:51:00 -0000
vti_extenderversion:SR|6.0.2.6551
vti_author:SR|JM-CHFU\\Jm.fu
vti_modifiedby:SR|JM-CHFU\\Jm.fu
vti_timecreated:TR|22 Apr 2007 13:51:00 -0000
vti_cacheddtm:TX|22 Apr 2007 13:51:00 -0000
vti_filesize:IR|32931
vti_cachedlinkinfo:VX|H|Other.Asp A|Other.Asp A|Other.Asp A|Other.Asp A|Other.Asp A|Other.Asp A|Other.Asp A|Other.Asp A|Other.Asp S|Inc/Fun.js A|Other.Asp S|../images/UbbPic/1.gif S|../images/UbbPic/2.gif S|../images/UbbPic/3.gif S|../images/UbbPic/4.gif S|../images/UbbPic/5.gif S|../images/UbbPic/6.gif S|../images/UbbPic/7.gif S|../images/UbbPic/8.gif S|../images/UbbPic/9.gif S|../images/UbbPic/10.gif S|../images/UbbPic/11.gif S|../images/UbbPic/12.gif S|../images/UbbPic/13.gif S|../images/UbbPic/14.gif S|../images/UbbPic/15.gif S|../images/UbbPic/16.gif S|../images/plus.gif S|../images/minus.gif S|about:blank A|Other.Asp S|../images/hr1.gif
vti_cachedsvcrellinks:VX|FHUS|bbs/Admin/Other.Asp FAUS|bbs/Admin/Other.Asp FAUS|bbs/Admin/Other.Asp FAUS|bbs/Admin/Other.Asp FAUS|bbs/Admin/Other.Asp FAUS|bbs/Admin/Other.Asp FAUS|bbs/Admin/Other.Asp FAUS|bbs/Admin/Other.Asp FAUS|bbs/Admin/Other.Asp NSUS|bbs/Admin/Inc/Fun.js FAUS|bbs/Admin/Other.Asp FSUS|bbs/images/UbbPic/1.gif FSUS|bbs/images/UbbPic/2.gif FSUS|bbs/images/UbbPic/3.gif FSUS|bbs/images/UbbPic/4.gif FSUS|bbs/images/UbbPic/5.gif FSUS|bbs/images/UbbPic/6.gif FSUS|bbs/images/UbbPic/7.gif FSUS|bbs/images/UbbPic/8.gif FSUS|bbs/images/UbbPic/9.gif FSUS|bbs/images/UbbPic/10.gif FSUS|bbs/images/UbbPic/11.gif FSUS|bbs/images/UbbPic/12.gif FSUS|bbs/images/UbbPic/13.gif FSUS|bbs/images/UbbPic/14.gif FSUS|bbs/images/UbbPic/15.gif FSUS|bbs/images/UbbPic/16.gif FSUS|bbs/images/plus.gif FSUS|bbs/images/minus.gif NSUS|about:blank FAUS|bbs/Admin/Other.Asp FSUS|bbs/images/hr1.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|gb2312
vti_backlinkinfo:VX|bbs/Admin/Index.Asp bbs/Admin/Other.Asp
