vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Apr 2007 13:51:00 -0000
vti_extenderversion:SR|6.0.2.6551
vti_author:SR|JM-CHFU\\Jm.fu
vti_modifiedby:SR|JM-CHFU\\Jm.fu
vti_timecreated:TR|22 Apr 2007 13:51:00 -0000
vti_cacheddtm:TX|22 Apr 2007 13:51:00 -0000
vti_filesize:IR|10533
vti_cachedlinkinfo:VX|A|Plus.Asp H|<%=Rs(2)%> H|Plus.Asp S|../images/edit.gif H|Plus.Asp S|../images/del.gif A|Plus.Asp H|Plus.Asp S|../images/edit.gif H|Plus.Asp S|../images/del.gif A|Plus.Asp A|Plus.Asp
vti_cachedsvcrellinks:VX|FAUS|bbs/Admin/Plus.Asp UHUS|<%=Rs(2)%> FHUS|bbs/Admin/Plus.Asp FSUS|bbs/images/edit.gif FHUS|bbs/Admin/Plus.Asp FSUS|bbs/images/del.gif FAUS|bbs/Admin/Plus.Asp FHUS|bbs/Admin/Plus.Asp FSUS|bbs/images/edit.gif FHUS|bbs/Admin/Plus.Asp FSUS|bbs/images/del.gif FAUS|bbs/Admin/Plus.Asp FAUS|bbs/Admin/Plus.Asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|gb2312
vti_backlinkinfo:VX|bbs/Admin/Index.Asp bbs/Admin/Plus.Asp
