vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Apr 2007 13:51:00 -0000
vti_extenderversion:SR|6.0.2.6551
vti_author:SR|JM-CHFU\\Jm.fu
vti_modifiedby:SR|JM-CHFU\\Jm.fu
vti_timecreated:TR|22 Apr 2007 13:51:00 -0000
vti_cacheddtm:TX|22 Apr 2007 13:51:00 -0000
vti_filesize:IR|14858
vti_cachedlinkinfo:VX|H|Template.Asp H|Template.Asp H|Template.Asp H|Template.Asp A|Template.Asp H|Template.Asp S|../images/edit.gif H|Template.Asp S|../images/del.gif A|Template.Asp A|Template.Asp A|Template.Asp A|Template.Asp
vti_cachedsvcrellinks:VX|FHUS|bbs/Admin/Template.Asp FHUS|bbs/Admin/Template.Asp FHUS|bbs/Admin/Template.Asp FHUS|bbs/Admin/Template.Asp FAUS|bbs/Admin/Template.Asp FHUS|bbs/Admin/Template.Asp FSUS|bbs/images/edit.gif FHUS|bbs/Admin/Template.Asp FSUS|bbs/images/del.gif FAUS|bbs/Admin/Template.Asp FAUS|bbs/Admin/Template.Asp FAUS|bbs/Admin/Template.Asp FAUS|bbs/Admin/Template.Asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|gb2312
vti_backlinkinfo:VX|bbs/Admin/Template.Asp
